config/routes.rb
Rails.application.routes.draw do
  resources :offers
  resources :tasks
  resources :products
  resources :participants_tasks

  root 'offers#index'

end

app/models/offer.rb
class Offer < ActiveRecord::Base

	has_many :tasks
	has_many :participants, dependent: :destroy


	def crud_participants(no_participants)
		difference = self.participants.count - no_participants
		difference = difference.abs

    	# Create rows for tasks and participants in db
    	if self.participants.count > no_participants 
    		#puts "remove participants"
        	difference.times {self.participants.last.delete}

    	elsif self.participants.count < no_participants
    		#puts "add participants"
    		difference.times { Participant.create(:offer_id => self.id, :on_switch => 0) }
    	elsif self.participants.count == 0
    		#create	
        	no_participants.times { Participant.create(:offer_id => self.id, :on_switch => 0) }
        elsif self.participants.count = no_participants
        	puts "do nothing"	
        end	
	end	

	
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :offer
end

app/models/participants_task.rb
class ParticipantsTask < ActiveRecord::Base



end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :products_tasks
	has_many :tasks, :through => :products_tasks
end

app/models/products_task.rb
class ProductsTask < ActiveRecord::Base
  belongs_to :product
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base

	attr_accessor :no_products

	belongs_to :offer
	belongs_to :task_type
	has_many :products_tasks
	has_many :products, :through => :products_tasks

	def self.order_by_task_type
		order("task_type_id ASC")
	end 
	
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base

	has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  #layout "offer"

  # GET /offers
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  def show
    @offer = Offer.find(params[:id])
    @eachparts = @offer.participants
    @eachtasks = @offer.tasks.order_by_task_type
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  def create

  # Instantiate new object using form parameters
    @offer = Offer.new(offer_params)

    # Save the object
    respond_to do |format|

      if @offer.save
      # If save succeeds, redirect to index action

        @offer.crud_participants(offer_params[:max_participants].to_i)

        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
      else 
      # If save fails, redisplay form so user can fix problems

        format.html { render :new }

      end
    end
  end

  # PATCH/PUT /offers/1
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        @offer.crud_participants(offer_params[:max_participants].to_i)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /offers/1
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer 
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:name, :min_participants, :max_participants, :start_at, :end_at)
    end
end

app/controllers/participants_tasks_controller.rb
class ParticipantsTasksController < ApplicationController
	
	def index
	end 

	def show
		# This should all go in the model
		params[:tasks].collect do |index, item|

			item.each do |inn, it|

				if !ParticipantsTask.exists?(:task_id => index, :participant_id => inn, :offer_id => params[:offer_id])
					#create
					@parttask = ParticipantsTask.create(:task_id => index, :participant_id => inn, :offer_id => params[:offer_id], :value => it)
				else
					#@fin = ParticipantsTask.find(:task_id => index, :participant_id => inn, :offer_id => params[:offer_id])
					#@fin.save
					puts "Right here #{@fin.id}"
				end
					#update
					# @fin.each do |pt|
					# 	puts "Task id: #{pt.task_id}, Participant id: #{pt.participant_id}, Value: #{pt.value}"
					# end
			end
			
		end

		#perform validation here before redirect
		redirect_to offer_path(params[:offer_id])
	end 


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	def index

	end

	def new
		#@product = Product.new
	end

	def create
		params[:name].each do |p|
			@task = Task.create(:name => p[1], :offer_id => offer_id, :offer_id => params[:offer_id], :task_type_id => params[:task_type_id])
			@task.save
		end
		redirect_to offer_path(:id => params[:offer_id])
	end


	private

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def show
		@task = Task.find(params[:id])
		
		@product = Product.new
		
	end

	def create
		#puts "TASK ID: #{params[:task][:task_type_id]}"
		type_id = params[:task][:task_type_id].to_i

		if type_id == 1 # Compulsory

			#create task and product with the same name
			@task = Task.create(task_params)
			redirect_to offers_path(params[:task][:offer_id])

		elsif type_id == 2 # Optional
			
			# this redirects to show.html.erb view, where the task logic happens
			redirect_to task_path(@task, 
				:no_products => task_params[:no_products], 
				:id => task_params[:offer_id])

		elsif type_id == 3 #Either-Or

		else 
			redirect_to offer_path(params[:task][:offer_id]), notice: 'Something went wrong'
		end		
	end

	def new
		@task = Task.new
		#redirect_to offer_path(@task.offer_id)
	end

	def destroy
	@task = Task.find(params[:id])
    @task.destroy
    	respond_to do |format|
      		format.html { redirect_to offer_path(@task.offer_id), notice: 'Task was successfully destroyed.' }
      	end
    end

    private


    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :offer_id, :task_type_id, :on_switch, :quota, :no_products)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/participants_tasks_helper.rb
module ParticipantsTasksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Ei Group Buying Engine</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<div id="header">
			<h1>EiGB Engine</h1>
		</div>
		<div id="main">
			<% if !notice.blank? %>
				<p id="notice"><%= notice %></p>
			<% end %>
			<div id="content">
				<%= yield %>
			</div>
		</div>
		<div id="footer">
			<p>&copy; 2014 Entertainment Intelligence</p>
		</div>
	</body>
</html>

app/views/layouts/offer.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Ei Group Buying: Offer</title>
	</head>
	<body>
		<div id="header">
			<h1>EiGB Engine</h1>
		</div>
		<div id="main">
			<% if !notice.blank? %>
				<p id="notice"><%= notice %></p>
			<% end %>
			<div id="content">
				<%= yield %>
			</div>
		</div>
		<div id="footer">
			<p>&copy; 2014 Entertainment Intelligence</p>
		</div>
	</body>
</html>

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :min_participants %><br>
    <%= f.number_field :min_participants %>
  </div>
   <div class="field">
    <%= f.label :max_participants %><br>
    <%= f.number_field :max_participants %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.date_select :start_at %> <small>(Optional)</small>
  </div>
  <div class="field">
    <%= f.label :end_at %><br>
    <%= f.date_select :end_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h2>Offers</h2>
<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
      <th>Min participants</th>
      <th>Max participants</th>
      <th>Start at</th>
      <th>End at</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= link_to offer.name, offer %></td>
        <td><%= offer.tasks.count %></td>
        <td><%= offer.min_participants %></td>
        <td><%= offer.max_participants %></td>
        <td><%= offer.start_at.strftime("%d/%m/%Y") %></td>
        <td><%= offer.end_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Remove', offer, method: :delete, data: { confirm: "Are you sure you want to remove #{offer.name}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<table border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th>Offer</th>
      <th>Participants (Min)</th>
      <th>Participants (Max)</th>
      <th>Start Date</th>
      <th>End Date</th>
    </tr>
  </thead>
  <tbody align="center">
    <tr>
      <td>
        <%= @offer.id %>
      </td>
      <td>
        <%= @offer.name %>
      </td>
      <td>
        <%= @offer.min_participants %>
      </td>
      <td>
        <%= @offer.max_participants %>
      </td>
      <td>
        <%= @offer.start_at.strftime("%d/%m/%Y") %>
      </td>
      <td>
        <%= @offer.end_at.strftime("%d/%m/%Y") %>
      </td>
    </tr>
  </tbody>
</table>

<h3>Tasks:</h3>
<%#= @party = ParticipantsTask.find_by(offer_id: 53).value %>
<table border="2" cellpadding="10" cellspacing="2">
  <thead>
    <tr>
      <th colspan="2">Task</th>
      <th colspan="<%= @eachparts.count %>">Participants</th>
      <th rowspan="2"></th>
    </tr>
    <tr>
      <th>Type</th>
      <th>Name</th>
        <% i = 1 %>
        <% @eachparts.each do |part| %>
        <th width="75">User <%= i %></th>
        <% i = i+1 %>
      <% end %>
    </tr>
  </thead>
    <tbody align="center">
<%= form_for(participants_task_path(@offer.id), method: "get") do %>
<%= hidden_field_tag :offer_id, value = @offer.id %>
    <% @eachtasks.each do |task| %>
      <tr>
        <td>
          <strong><%= task.task_type.name %></strong>
        </td>
        <td>
          <%= task.name %>
        </td>
          <% @eachparts.each do |count| %>
          <td>
              <% if ParticipantsTask.exists?(:task_id => task.id, :participant_id => count.id, :offer_id => @offer.id, :value => true) %>
                <%#= check_box("tasks[#{task.id}][#{count.id}]", checked_value = "1", checked = true ) %>
                <strong>✓</strong>
                <%= check_box("tasks[#{task.id}]", "#{count.id}") %>
              <% else %>
                <%#= check_box_tag("tasks[#{task.id}][#{count.id}]", value = "1") %>
                <%= check_box("tasks[#{task.id}]", "#{count.id}") %>
              <% end %>
          </td>
          <% end %>  
        <td>
          <%= link_to 'Remove', task, method: :delete, data: { confirm: "Are you sure you want to remove #{task.name}?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
  <%= submit_tag("Validate Offer") %>
<% end %>
<br>
<h4>New Task:</h4>
<%= form_tag(new_task_path, method: "get") do %>
<%= select_tag("task_type_id", options_for_select([['Compulsory', 1], ['Optional', 2], ['Either-Or', 3]])) %>
<%= hidden_field_tag("offer_id", @offer.id) %>
<%= submit_tag("Add") %> 
<% end %>
<br>



<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

app/views/participants_tasks/show.html.erb
<h1>Participants Tasks</h1>
<%# params[:tasks].each do |p| %>
<%# params[:tasks].collect do |index, item| %>
	<%# item.each do |inn, it| %>
	<%#= "#{index}: #{inn}" %>
	<%# end %>
<%# end %>

app/views/products/new.html.erb
<h1>New Product</h1>
<h2><%= params %></h2>

app/views/products/show.html.erb
<h1>Hello</h1>

app/views/tasks/index.html.erb
<% puts params %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
	<%= f.hidden_field :task_type_id, value: params[:task_type_id] %>
	<%= f.hidden_field :offer_id, value: params[:offer_id] %>
	<% if params[:task_type_id].to_i == 1 %>
		<h2>Create new Compulsory task</h2>
		  <div class="field">
		    <%= f.label :name %><br>
		    <%= f.text_field :name %>
		  </div>
	<% elsif params[:task_type_id].to_i == 2 %>
	<h2>Create new Optional task</h2>
		<div class="field">
		    <%= f.label :name %><br>
		    <%= f.text_field :name %>
		  </div>
		<div class="field">
		    <%= f.label "No, Produts" %><br>
		    <%= f.number_field :no_products %>
		</div>
		<div class="field">
		    <%= f.label :quota %><br>
		    <%= f.number_field :quota %>
		</div>

	<% elsif params[:task_type_id].to_i == 3 %>

	<h2>Create new Either-Or task</h2>
		<div class="field">
		    <%= f.label :name %><br>
		    <%= f.text_field :name %>
		  </div>
		<div class="field">
		    <%= f.label "No of Fields" %><br>
		    <%= f.number_field :no_products %>
		</div>
		<div class="field">
		    <%= f.label "No of Compulsories" %><br>
		    <%= f.number_field :quota %> <small>(Must be < No of (Fields)</small>
		</div>

	<% else %>
		<p><strong>Error: Task ype not known</strong></p>
	<% end %>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/tasks/show.html.erb
<h1>Add Tasks</h1>
<% i=1 %>
<%= form_for(@product) do |f| %>		
	<% params[:no_products].to_i.times do %>
		<div class="field">
		    <%= f.label "Product #{i}" %><br>
		    <%= text_field "name", "#{i-1}" %>
		</div>
	<% i+=1 %>	
	<% end %>
		<div class="actions">
			<%= f.submit "Add" %>
		</div>
<% end %>